name: mobile_web
description: "코박 Flutter Web App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cobak_logo.png
    - assets/profile.png
    - assets/robot.png
    - assets/bell.png
    - assets/search.png
    - assets/banner.png
    - assets/home.png
    - assets/community.png
    - assets/space.png
    - assets/clock.png
    - assets/invest.png
    - assets/fire.png
    - assets/top_banner.png
    - assets/space2.png
    - assets/moneybag.png
    - assets/stamp.png
    - assets/stamp2.png
    - assets/wallet2.png
    - assets/arrow_back.png
    - assets/image2823.png
    - assets/image2824.png
    - assets/write.png
    - assets/comment.png
    - assets/chart.png
    - assets/image2833.png
    - assets/image2834.png
    - "assets/Live_main 1.png"
    - assets/realtime_main.png
    - assets/mission_main.png
    - assets/stock_main.png
    - assets/toolbox_main.png
    - assets/business_main.png
    - assets/rank_main.png
    - "assets/출석 rocket.png"
    - assets/rcket_click.png
